### PR TITLE
Group event wiki page notes

### PR DESCRIPTION
**Pull request by gRegorLove**
This displays event wiki pages (pages starting with `/events`) in their own section and displays them by event name, then a list of event dates as links.

Example:
Homebrew Website Club - Pacific: [2023-01-25](https://indieweb.org/events/2023-01-25-hwc-pacific), [2023-01-11](https://indieweb.org/events/2023-01-11-hwc-pacific)
Homebrew Website Club Europe/London: [2023-01-18](https://indieweb.org/events/2023-01-18-hwc-europe)

It also adds phpunit and some unit tests for the new functions I added.

I also fixed the `uasort()` usage and autoloaded functions.php so the extra `require_once` wasn't needed.

### CODE REVIEW

**Review by martymcguire — APPROVED** [review]
This looks good to my eyes. I also pulled this down to test locally. I don't often PHP directly on my laptop (Pop!_OS (ubuntu) 22.04) so I had to install some stuff:

```
sudo apt install composer php8.1-xml
```

I also had the following extra setup steps post-composer-install before tests would run:

```
php ./vendor/tantek/cassis/post-process.php
cp config.template.php config.php
```

Then tests ran fine:

```
./vendor/bin/phpunit tests/
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

............                                                      12 / 12 (100%)

Time: 00:00.002, Memory: 6.00 MB

OK (12 tests, 20 assertions)
```

**Comment by gRegorLove** [comment]
Once https://github.com/tantek/cassis/pull/40 is merged, we should try these unit tests again under PHP8+ to ensure we don't have to manually run `php ./vendor/tantek/cassis/post-process.php`

**Comment by gRegorLove** [comment]
@martymcguire I updated the readme and added a command line test to generate the wiki summary so it can be manually reviewed -- specifically to see the event grouping in this case. Can you try it out?

**Review by martymcguire — APPROVED** [review]
Thanks @gRegorLove ! These updates helped with testing. One nit: the output of running `php ./tests/test-wiki-summary.php` says:

```
Results saved to wiki-summary-output.html
```

The output file is actually saved to `tests/wiki-summary-output.html`. A very small thing!

Let me know if there's anything specific you need from me, here!

**Comment by gRegorLove** [comment]
@martymcguire Thanks, just corrected that message.

I think the only thing left is to manually review that output HTML to make sure the event grouping appears correct like in https://github.com/indieweb/this-week/pull/24#issue-1560675969. It looked good in my testing.

If everything looks good, I think this is OK for @aaronpk to deploy.

**Pull request merged**
